<a href="https://colab.research.google.com/github/anushkaa-10/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np

In [55]:
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [53]:
arr2 = np.array([[4,2,5],[1,4,3],[9,7,8]])

In [54]:
arr3 = np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])

In [56]:
arr1+arr2

array([[ 5,  4,  8],
       [ 5,  9,  9],
       [16, 15, 17]])

In [57]:
arr1 + arr3

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [42]:
arr2 * arr1

array([[ 4,  4, 15],
       [ 4, 20, 18],
       [63, 56, 72]])

In [43]:
arr1.dot(arr2)

array([[ 33,  31,  35],
       [ 75,  70,  83],
       [117, 109, 131]])

In [44]:
arr2.dot(arr1)

array([[ 47,  58,  69],
       [ 38,  46,  54],
       [ 93, 117, 141]])

In [45]:
arr1[:2,:2]

array([[1, 2],
       [4, 5]])

In [46]:
nums = np.array([[4,3,1,8],[9,0,6,7],[7,6,2,8]])

In [47]:
nums

array([[4, 3, 1, 8],
       [9, 0, 6, 7],
       [7, 6, 2, 8]])

In [48]:
np.sort(nums,axis=1,kind='mergesort')

array([[1, 3, 4, 8],
       [0, 6, 7, 9],
       [2, 6, 7, 8]])

In [49]:
np.sort(nums,axis=0,kind='mregesort')

array([[4, 0, 1, 7],
       [7, 3, 2, 8],
       [9, 6, 6, 8]])

In [51]:
c = np.array([6,7,5,8])
d = np.array([4,3,7,8])

In [52]:
pro = c.dot(d)
print(pro)

144
